const categories = [
    // Topic: website
    {
        id: 1,
        name: "Website",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Kan je de website vinden?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "Kan je alle informatie vinden op de website?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "In hoeverre ben je in staat om de website te navigeren?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe ervaar jij de website? Prettig/onprettig in gebruik?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 5,
                name: "In hoeverre voel jij je welkom op de website?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: entree
    {
        id: 2,
        name: "Entree",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Hoe is de route naar het Gemeentehuis Rotterdam toe? Kon je de entree vinden?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "In hoeverre is de entree duidelijk? Weet je wat je moet doen? Waar je heen moet gaan en waar je informatie kunt krijgen?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Hoe kom je binnen? Zijn hierbij obstakels?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe ervaar je de entree? Prettig/onprettig in gebruik?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 5,
                name: "Hoe gaat het personeel met je om?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: receptie
    {
        id: 3,
        name: "Receptie",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Hoe is de route naar de receptie? Kan je de receptie vinden?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "Hoe kom je binnen? Zijn hierbij obstakels?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Hoe ervaar jij de receptie? Prettig/onprettig in gebruik?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe gaat het personeel met je om?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: zalen en hallen
    {
        id: 4,
        name: "Zalen en hallen",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Hoe is de route naar de verschillende zalen? Kan je deze vinden?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "In hoeverre kan je door de zalen navigeren? Kan je de juiste informatie vinden?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Hoe kom je binnen? Zijn hierbij obstakels?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe ervaar jij de zalen? Prettig/onprettig in gebruik? Waarom?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 5,
                name: "Hoe gaat het personeel met je om?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: toilet
    {
        id: 5,
        name: "Toilet",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Hoe is de route naar het toilet toe? Kon je het toilet vinden?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "Kun je het toilet, de kraan, zeep etc. goed gebruiken?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Hoe kom je binnen? Zijn hierbij obstakels?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe ervaar je het toilet?  Prettig/onprettig in gebruik?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 5,
                name: "Hoe gaat het personeel met je om?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: stadhuistuin
    {
        id: 6,
        name: "Stadhuistuin",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Kan je de stadhuistuin vinden? Hoe is de route hiernaartoe?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "In hoeverre kan je je door de stadhuistuin navigeren? Zijn hierbij obstakels?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Hoe ervaar jij de museumwinkel? Prettig/onprettig in gebruik?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe gaat het personeel met je om?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: wegwijzing en paden
    {
        id: 7,
        name: "Wegwijzing en paden",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Kun je je (voldoende) oriënteren? Zijn de voor jou belangrijke zaken (zoals bijvoorbeeld de prullenbak) vindbaar?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "Is voor jou duidelijk waar je wel en niet mag/kunt lopen?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Kom je obstakels tegen onderweg?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Hoe ervaar jij de paden in het stadhuis?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 5,
                name: "Hoe gaat het personeel met je om?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
    // Topic: algemeen
    {
        id: 8,
        name: "Algemeen",
        fullyCompleted: false,
        questions: [
            {
                id: 1,
                name: "Hoe vind je in het algemeen de beleving van het stadhuis, de zalen en de onderdelen als de tuin?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 2,
                name: "Hoe vind je in het algemeen de bejegening van het personeel van het museum?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 3,
                name: "Welk eindcijfer (schaal van 1 tot 10) geef je het museum in het algemeen qua toegankelijkheid?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
            {
                id: 4,
                name: "Wil je verder nog iets kwijt?",
                standardAnswer: "",
                answer: "",
                recordedAnswer:[],
                status: 0,
            },
        ],
    },
];

module.exports = categories;